# Generated by Django 3.1.7 on 2021-02-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stammdaten',
            name='durability',
            field=models.IntegerField(default=720),
        ),
        migrations.AddField(
            model_name='stammdaten',
            name='durability_open',
            field=models.IntegerField(default=720),
        ),
        migrations.AddField(
            model_name='stammdaten',
            name='storage_temperature',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='stammdaten',
            name='storage_temperature_open',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='stammdaten',
            name='unit',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Lagerinhalt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('day_purchased', models.DateField(verbose_name='date purchased')),
                ('day_opened', models.DateField(verbose_name='date opened')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stammdaten')),
            ],
        ),
    ]
